const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const seedCuisines = [
  { value: "italian", label: "Italian" },
  { value: "french", label: "French" },
  { value: "spanish", label: "Spanish" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "indian", label: "Indian" },
  { value: "thai", label: "Thai" },
  { value: "mexican", label: "Mexican" },
  { value: "greek", label: "Greek" },
  { value: "turkish", label: "Turkish" },
  { value: "moroccan", label: "Moroccan" },
  { value: "korean", label: "Korean" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "brazilian", label: "Brazilian" },
  { value: "ethiopian", label: "Ethiopian" },
  { value: "peruvian", label: "Peruvian" },
  { value: "russian", label: "Russian" },
  { value: "american", label: "American" },
  { value: "canadian", label: "Canadian" },
  { value: "german", label: "German" },
  { value: "austrian", label: "Austrian" },
  { value: "polish", label: "Polish" },
  { value: "hungarian", label: "Hungarian" },
  { value: "egyptian", label: "Egyptian" },
  { value: "south_african", label: "South African" },
  { value: "nigerian", label: "Nigerian" },
  { value: "australian", label: "Australian" },
  { value: "argentinian", label: "Argentinian" },
  { value: "filipino", label: "Filipino" },
  { value: "indonesian", label: "Indonesian" },
  { value: "malaysian", label: "Malaysian" },
  { value: "persian", label: "Persian" },
  { value: "israeli", label: "Israeli" },
  { value: "lebanese", label: "Lebanese" },
  { value: "afghan", label: "Afghan" },
  { value: "albanian", label: "Albanian" },
  { value: "algerian", label: "Algerian" },
  { value: "andorran", label: "Andorran" },
  { value: "angolan", label: "Angolan" },
  { value: "armenian", label: "Armenian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "bahamian", label: "Bahamian" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "barbadian", label: "Barbadian" },
  { value: "belarusian", label: "Belarusian" },
  { value: "belgian", label: "Belgian" },
  { value: "belizean", label: "Belizean" },
  { value: "beninese", label: "Beninese" },
  { value: "bhutanese", label: "Bhutanese" },
  { value: "bolivian", label: "Bolivian" },
  { value: "bosnian", label: "Bosnian" },
  { value: "botswanan", label: "Botswanan" },
  { value: "bruneian", label: "Bruneian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "burkinabe", label: "Burkinabe" },
  { value: "burmese", label: "Burmese" },
  { value: "burundian", label: "Burundian" },
  { value: "cambodian", label: "Cambodian" },
  { value: "cameroonian", label: "Cameroonian" },
  { value: "cape_verdean", label: "Cape Verdean" },
  { value: "central_african", label: "Central African" },
  { value: "chadian", label: "Chadian" },
  { value: "chilean", label: "Chilean" },
  { value: "colombian", label: "Colombian" },
  { value: "comoran", label: "Comoran" },
  { value: "congolese", label: "Congolese" },
  { value: "costa_rican", label: "Costa Rican" },
  { value: "croatian", label: "Croatian" },
  { value: "cuban", label: "Cuban" },
  { value: "cypriot", label: "Cypriot" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "djiboutian", label: "Djiboutian" },
  { value: "dominican", label: "Dominican" },
  { value: "dutch", label: "Dutch" },
  { value: "ecuadorian", label: "Ecuadorian" },
  { value: "salvadoran", label: "Salvadoran" },
  { value: "equatorial_guinean", label: "Equatorial Guinean" },
  { value: "eritrean", label: "Eritrean" },
  { value: "estonian", label: "Estonian" },
  { value: "eswatini", label: "Eswatini" },
  { value: "fijian", label: "Fijian" },
  { value: "finnish", label: "Finnish" },
  { value: "gabonese", label: "Gabonese" },
  { value: "gambian", label: "Gambian" },
  { value: "georgian", label: "Georgian" },
  { value: "ghanaian", label: "Ghanaian" },
  { value: "grenadian", label: "Grenadian" },
  { value: "guatemalan", label: "Guatemalan" },
  { value: "guinean", label: "Guinean" },
  { value: "guyanese", label: "Guyanese" },
  { value: "haitian", label: "Haitian" },
  { value: "honduran", label: "Honduran" },
  { value: "icelandic", label: "Icelandic" },
  { value: "iraqi", label: "Iraqi" },
  { value: "irish", label: "Irish" },
  { value: "ivorian", label: "Ivorian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "jordanian", label: "Jordanian" },
  { value: "kazakhstani", label: "Kazakhstani" },
  { value: "kenyan", label: "Kenyan" },
  { value: "kiribati", label: "Kiribati" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "kyrgyzstani", label: "Kyrgyzstani" },
  { value: "laotian", label: "Laotian" },
  { value: "latvian", label: "Latvian" },
  { value: "liberian", label: "Liberian" },
  { value: "libyan", label: "Libyan" },
  { value: "liechtensteiner", label: "Liechtensteiner" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "luxembourgish", label: "Luxembourgish" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malawian", label: "Malawian" },
  { value: "maldivian", label: "Maldivian" },
  { value: "malian", label: "Malian" },
  { value: "maltese", label: "Maltese" },
  { value: "marshallese", label: "Marshallese" },
  { value: "mauritanian", label: "Mauritanian" },
  { value: "mauritian", label: "Mauritian" },
  { value: "micronesian", label: "Micronesian" },
  { value: "moldovan", label: "Moldovan" },
  { value: "monacan", label: "Monacan" },
  { value: "mongolian", label: "Mongolian" },
  { value: "montenegrin", label: "Montenegrin" },
  { value: "mozambican", label: "Mozambican" },
  { value: "namibian", label: "Namibian" },
  { value: "nauruan", label: "Nauruan" },
  { value: "nepalese", label: "Nepalese" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "nicaraguan", label: "Nicaraguan" },
  { value: "nigerien", label: "Nigerien" },
  { value: "north_korean", label: "North Korean" },
  { value: "norwegian", label: "Norwegian" },
  { value: "omani", label: "Omani" },
  { value: "pakistani", label: "Pakistani" },
  { value: "palauan", label: "Palauan" },
  { value: "panamanian", label: "Panamanian" },
  { value: "papua_new_guinean", label: "Papua New Guinean" },
  { value: "paraguayan", label: "Paraguayan" },
  { value: "portuguese", label: "Portuguese" },
  { value: "qatari", label: "Qatari" },
  { value: "romanian", label: "Romanian" },
  { value: "rwandan", label: "Rwandan" },
  { value: "saint_lucian", label: "Saint Lucian" },
  { value: "saint_vincentian", label: "Saint Vincentian" },
  { value: "samoan", label: "Samoan" },
  { value: "san_marinese", label: "San Marinese" },
  { value: "sao_tomean", label: "Sao Tomean" },
  { value: "saudi_arabian", label: "Saudi Arabian" },
  { value: "senegalese", label: "Senegalese" },
];

const seedDishes = [
  { value: "Pizza", label: "Pizza" },
  { value: "Burger", label: "Burger" },
  { value: "Sushi", label: "Sushi" },
  { value: "Pasta", label: "Pasta" },
  { value: "Tacos", label: "Tacos" },
  { value: "Salad", label: "Salad" },
  { value: "Ramen", label: "Ramen" },
  { value: "Paella", label: "Paella" },
  { value: "Curry", label: "Curry" },
  { value: "Steak", label: "Steak" },
  { value: "Lasagna", label: "Lasagna" },
  { value: "Dumplings", label: "Dumplings" },
  { value: "Pho", label: "Pho" },
  { value: "Falafel", label: "Falafel" },
  { value: "Gyros", label: "Gyros" },
  { value: "Burrito", label: "Burrito" },
  { value: "Pancakes", label: "Pancakes" },
  { value: "Waffles", label: "Waffles" },
  { value: "Croissant", label: "Croissant" },
  { value: "Bagel", label: "Bagel" },
  { value: "Donuts", label: "Donuts" },
  { value: "Hot Dog", label: "Hot Dog" },
  { value: "Fried Chicken", label: "Fried Chicken" },
  { value: "Barbecue", label: "Barbecue" },
  { value: "Fish and Chips", label: "Fish and Chips" },
  { value: "Tofu Stir Fry", label: "Tofu Stir Fry" },
  { value: "Risotto", label: "Risotto" },
  { value: "Biryani", label: "Biryani" },
  { value: "Pad Thai", label: "Pad Thai" },
  { value: "Peking Duck", label: "Peking Duck" },
  { value: "Spring Rolls", label: "Spring Rolls" },
  { value: "Fajitas", label: "Fajitas" },
  { value: "Enchiladas", label: "Enchiladas" },
  { value: "Quiche", label: "Quiche" },
  { value: "Tiramisu", label: "Tiramisu" },
  { value: "Cheesecake", label: "Cheesecake" },
  { value: "Baklava", label: "Baklava" },
  { value: "Apple Pie", label: "Apple Pie" },
  { value: "Churros", label: "Churros" },
  { value: "Brownies", label: "Brownies" },
  { value: "Macarons", label: "Macarons" },
  { value: "Gelato", label: "Gelato" },
  { value: "Sorbet", label: "Sorbet" },
  { value: "Crepes", label: "Crepes" },
  { value: "Poutine", label: "Poutine" },
  { value: "Shepherd's Pie", label: "Shepherd's Pie" },
  { value: "Carbonara", label: "Carbonara" },
  { value: "Ratatouille", label: "Ratatouille" },
  { value: "Bruschetta", label: "Bruschetta" },
  { value: "Schnitzel", label: "Schnitzel" },
  { value: "Kebab", label: "Kebab" },
  { value: "Bao Buns", label: "Bao Buns" },
  { value: "Dim Sum", label: "Dim Sum" },
  { value: "Ceviche", label: "Ceviche" },
  { value: "Chow Mein", label: "Chow Mein" },
  { value: "Kimchi", label: "Kimchi" },
  { value: "Bulgogi", label: "Bulgogi" },
  { value: "Goulash", label: "Goulash" },
  { value: "Pierogi", label: "Pierogi" },
  { value: "Borscht", label: "Borscht" },
  { value: "Stroopwafel", label: "Stroopwafel" },
  { value: "Moussaka", label: "Moussaka" },
  { value: "Empanadas", label: "Empanadas" },
  { value: "Arepa", label: "Arepa" },
  { value: "Pupusa", label: "Pupusa" },
  { value: "Samosa", label: "Samosa" },
  { value: "Kofta", label: "Kofta" },
  { value: "Shawarma", label: "Shawarma" },
  { value: "Hummus", label: "Hummus" },
  { value: "Tabbouleh", label: "Tabbouleh" },
  { value: "Dal", label: "Dal" },
  { value: "Tikka Masala", label: "Tikka Masala" },
  { value: "Butter Chicken", label: "Butter Chicken" },
  { value: "Rogan Josh", label: "Rogan Josh" },
  { value: "Vindaloo", label: "Vindaloo" },
  { value: "Jambalaya", label: "Jambalaya" },
  { value: "Gumbo", label: "Gumbo" },
  { value: "Po' Boy", label: "Po' Boy" },
  { value: "Beignets", label: "Beignets" },
  { value: "Fondue", label: "Fondue" },
  { value: "Raclette", label: "Raclette" },
  { value: "Sauerbraten", label: "Sauerbraten" },
  { value: "Wiener Schnitzel", label: "Wiener Schnitzel" },
  { value: "Spätzle", label: "Spätzle" },
  { value: "Rösti", label: "Rösti" },
  { value: "Frikadellen", label: "Frikadellen" },
  { value: "Coq au Vin", label: "Coq au Vin" },
  { value: "Bouillabaisse", label: "Bouillabaisse" },
  { value: "Escargot", label: "Escargot" },
  { value: "Ratatouille", label: "Ratatouille" },
  { value: "Gazpacho", label: "Gazpacho" },
  { value: "Pa amb tomàquet", label: "Pa amb tomàquet" },
  { value: "Tortilla Española", label: "Tortilla Española" },
  { value: "Lechon", label: "Lechon" },
  { value: "Adobo", label: "Adobo" },
  { value: "Sinigang", label: "Sinigang" },
  { value: "Banh Mi", label: "Banh Mi" },
  { value: "Pho", label: "Pho" },
  { value: "Tom Yum", label: "Tom Yum" },
  { value: "Massaman Curry", label: "Massaman Curry" },
];

const locationTypeData = [
  { value: "restaurant", label: "Restaurant" },
  { value: "takeaway", label: "Takeaway" },
  { value: "bar", label: "Bar" },
  { value: "cafe", label: "Cafe" },
  { value: "pub", label: "Pub" },
];

async function main() {
  console.log(`Start seeding ...`);

  for (const c of seedCuisines) {
    const cuisine = await prisma.cuisine.create({
      data: c,
    });
    console.log(`Created cuisine with id: ${cuisine.id}`);
  }

  for (const l of locationTypeData) {
    const locationType = await prisma.locationType.create({
      data: l,
    });
    console.log(`Created location with id: ${locationType.id}`);
  }

  for (const l of seedDishes) {
    const dish = await prisma.dish.create({
      data: l,
    });
    console.log(`Created dish with id: ${dish.id}`);
  }
  console.log(`Seeding finished.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
