const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const seedCuisines = [
  { value: "italian", label: "Italian" },
  { value: "french", label: "French" },
  { value: "spanish", label: "Spanish" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "indian", label: "Indian" },
  { value: "thai", label: "Thai" },
  { value: "mexican", label: "Mexican" },
  { value: "greek", label: "Greek" },
  { value: "turkish", label: "Turkish" },
  { value: "moroccan", label: "Moroccan" },
  { value: "korean", label: "Korean" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "brazilian", label: "Brazilian" },
  { value: "ethiopian", label: "Ethiopian" },
  { value: "peruvian", label: "Peruvian" },
  { value: "russian", label: "Russian" },
  { value: "american", label: "American" },
  { value: "canadian", label: "Canadian" },
  { value: "german", label: "German" },
  { value: "austrian", label: "Austrian" },
  { value: "polish", label: "Polish" },
  { value: "hungarian", label: "Hungarian" },
  { value: "egyptian", label: "Egyptian" },
  { value: "south_african", label: "South African" },
  { value: "nigerian", label: "Nigerian" },
  { value: "australian", label: "Australian" },
  { value: "argentinian", label: "Argentinian" },
  { value: "filipino", label: "Filipino" },
  { value: "indonesian", label: "Indonesian" },
  { value: "malaysian", label: "Malaysian" },
  { value: "persian", label: "Persian" },
  { value: "israeli", label: "Israeli" },
  { value: "lebanese", label: "Lebanese" },
  { value: "afghan", label: "Afghan" },
  { value: "albanian", label: "Albanian" },
  { value: "algerian", label: "Algerian" },
  { value: "andorran", label: "Andorran" },
  { value: "angolan", label: "Angolan" },
  { value: "armenian", label: "Armenian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "bahamian", label: "Bahamian" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "barbadian", label: "Barbadian" },
  { value: "belarusian", label: "Belarusian" },
  { value: "belgian", label: "Belgian" },
  { value: "belizean", label: "Belizean" },
  { value: "beninese", label: "Beninese" },
  { value: "bhutanese", label: "Bhutanese" },
  { value: "bolivian", label: "Bolivian" },
  { value: "bosnian", label: "Bosnian" },
  { value: "botswanan", label: "Botswanan" },
  { value: "bruneian", label: "Bruneian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "burkinabe", label: "Burkinabe" },
  { value: "burmese", label: "Burmese" },
  { value: "burundian", label: "Burundian" },
  { value: "cambodian", label: "Cambodian" },
  { value: "cameroonian", label: "Cameroonian" },
  { value: "cape_verdean", label: "Cape Verdean" },
  { value: "central_african", label: "Central African" },
  { value: "chadian", label: "Chadian" },
  { value: "chilean", label: "Chilean" },
  { value: "colombian", label: "Colombian" },
  { value: "comoran", label: "Comoran" },
  { value: "congolese", label: "Congolese" },
  { value: "costa_rican", label: "Costa Rican" },
  { value: "croatian", label: "Croatian" },
  { value: "cuban", label: "Cuban" },
  { value: "cypriot", label: "Cypriot" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "djiboutian", label: "Djiboutian" },
  { value: "dominican", label: "Dominican" },
  { value: "dutch", label: "Dutch" },
  { value: "ecuadorian", label: "Ecuadorian" },
  { value: "salvadoran", label: "Salvadoran" },
  { value: "equatorial_guinean", label: "Equatorial Guinean" },
  { value: "eritrean", label: "Eritrean" },
  { value: "estonian", label: "Estonian" },
  { value: "eswatini", label: "Eswatini" },
  { value: "fijian", label: "Fijian" },
  { value: "finnish", label: "Finnish" },
  { value: "gabonese", label: "Gabonese" },
  { value: "gambian", label: "Gambian" },
  { value: "georgian", label: "Georgian" },
  { value: "ghanaian", label: "Ghanaian" },
  { value: "grenadian", label: "Grenadian" },
  { value: "guatemalan", label: "Guatemalan" },
  { value: "guinean", label: "Guinean" },
  { value: "guyanese", label: "Guyanese" },
  { value: "haitian", label: "Haitian" },
  { value: "honduran", label: "Honduran" },
  { value: "icelandic", label: "Icelandic" },
  { value: "iraqi", label: "Iraqi" },
  { value: "irish", label: "Irish" },
  { value: "ivorian", label: "Ivorian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "jordanian", label: "Jordanian" },
  { value: "kazakhstani", label: "Kazakhstani" },
  { value: "kenyan", label: "Kenyan" },
  { value: "kiribati", label: "Kiribati" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "kyrgyzstani", label: "Kyrgyzstani" },
  { value: "laotian", label: "Laotian" },
  { value: "latvian", label: "Latvian" },
  { value: "liberian", label: "Liberian" },
  { value: "libyan", label: "Libyan" },
  { value: "liechtensteiner", label: "Liechtensteiner" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "luxembourgish", label: "Luxembourgish" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malawian", label: "Malawian" },
  { value: "maldivian", label: "Maldivian" },
  { value: "malian", label: "Malian" },
  { value: "maltese", label: "Maltese" },
  { value: "marshallese", label: "Marshallese" },
  { value: "mauritanian", label: "Mauritanian" },
  { value: "mauritian", label: "Mauritian" },
  { value: "micronesian", label: "Micronesian" },
  { value: "moldovan", label: "Moldovan" },
  { value: "monacan", label: "Monacan" },
  { value: "mongolian", label: "Mongolian" },
  { value: "montenegrin", label: "Montenegrin" },
  { value: "mozambican", label: "Mozambican" },
  { value: "namibian", label: "Namibian" },
  { value: "nauruan", label: "Nauruan" },
  { value: "nepalese", label: "Nepalese" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "nicaraguan", label: "Nicaraguan" },
  { value: "nigerien", label: "Nigerien" },
  { value: "north_korean", label: "North Korean" },
  { value: "norwegian", label: "Norwegian" },
  { value: "omani", label: "Omani" },
  { value: "pakistani", label: "Pakistani" },
  { value: "palauan", label: "Palauan" },
  { value: "panamanian", label: "Panamanian" },
  { value: "papua_new_guinean", label: "Papua New Guinean" },
  { value: "paraguayan", label: "Paraguayan" },
  { value: "portuguese", label: "Portuguese" },
  { value: "qatari", label: "Qatari" },
  { value: "romanian", label: "Romanian" },
  { value: "rwandan", label: "Rwandan" },
  { value: "saint_lucian", label: "Saint Lucian" },
  { value: "saint_vincentian", label: "Saint Vincentian" },
  { value: "samoan", label: "Samoan" },
  { value: "san_marinese", label: "San Marinese" },
  { value: "sao_tomean", label: "Sao Tomean" },
  { value: "saudi_arabian", label: "Saudi Arabian" },
  { value: "senegalese", label: "Senegalese" },
  { value: "coffee", label: "Coffee" },
  { value: "angolan", label: "Angolan" },
  { value: "cameroonian", label: "Cameroonian" },
  { value: "chadian", label: "Chadian" },
  { value: "congolese", label: "Congolese" },
  { value: "centrafrican", label: "Centrafrican" },
  { value: "equatorial_guinean", label: "Equatorial Guinean" },
  { value: "gabonese", label: "Gabonese" },
  { value: "santomean", label: "Santomean" },
  { value: "burundian", label: "Burundian" },
  { value: "comorian", label: "Comorian" },
  { value: "djiboutian", label: "Djiboutian" },
  { value: "eritrean", label: "Eritrean" },
  { value: "ethiopian", label: "Ethiopian" },
  { value: "ethiopian_jewish", label: "Ethiopian Jewish" },
  { value: "kenyan", label: "Kenyan" },
  { value: "maasai", label: "Maasai" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malawian", label: "Malawian" },
  { value: "mauritian", label: "Mauritian" },
  { value: "mozambican", label: "Mozambican" },
  { value: "rwandan", label: "Rwandan" },
  { value: "seychellois", label: "Seychellois" },
  { value: "somali", label: "Somali" },
  { value: "south_sudanese", label: "South Sudanese" },
  { value: "tanzanian", label: "Tanzanian" },
  { value: "zanzibari", label: "Zanzibari" },
  { value: "ugandan", label: "Ugandan" },
  { value: "zambian", label: "Zambian" },
  { value: "zimbabwean", label: "Zimbabwean" },
  { value: "algerian", label: "Algerian" },
  { value: "berber", label: "Berber" },
  { value: "egyptian", label: "Egyptian" },
  { value: "libyan", label: "Libyan" },
  { value: "moroccan", label: "Moroccan" },
  { value: "sudanese", label: "Sudanese" },
  { value: "tunisian", label: "Tunisian" },
  { value: "western_saharan", label: "Western Saharan" },
  { value: "botswana", label: "Botswana" },
  { value: "eswatini", label: "Eswatini" },
  { value: "lesotho", label: "Lesotho" },
  { value: "namibian", label: "Namibian" },
  { value: "south_african", label: "South African" },
  { value: "benin", label: "Benin" },
  { value: "burkinabe", label: "Burkinabé" },
  { value: "cape_verdean", label: "Cape Verdean" },
  { value: "gambian", label: "Gambian" },
  { value: "ghanaian", label: "Ghanaian" },
  { value: "guinean", label: "Guinean" },
  { value: "guinea_bissauan", label: "Guinea-Bissauan" },
  { value: "ivorian", label: "Ivorian" },
  { value: "liberian", label: "Liberian" },
  { value: "malian", label: "Malian" },
  { value: "mauritanian", label: "Mauritanian" },
  { value: "niger", label: "Niger" },
  { value: "nigerian", label: "Nigerian" },
  { value: "saint_helenian", label: "Saint Helenian" },
  { value: "senegalese", label: "Senegalese" },
  { value: "sierra_leone", label: "Sierra Leone" },
  { value: "togolese", label: "Togolese" },
  { value: "latin_american", label: "Latin American" },
  { value: "native_american", label: "Native American" },
  { value: "inuit", label: "Inuit" },
  { value: "tlingit", label: "Tlingit" },
  { value: "bermudian", label: "Bermudian" },
  { value: "canadian", label: "Canadian" },
  { value: "maritime", label: "Cuisine of the Maritimes" },
  { value: "quebec", label: "Cuisine of Quebec" },
  { value: "toronto", label: "Cuisine of Toronto" },
  { value: "greenlandic", label: "Greenlandic" },
  { value: "mexican", label: "Mexican" },
  { value: "chiapas", label: "Cuisine of Chiapas" },
  { value: "oaxacan", label: "Oaxacan" },
  { value: "veracruz", label: "Cuisine of Veracruz" },
  { value: "midwestern_american", label: "Midwestern American" },
  { value: "chicago", label: "Cuisine of Chicago" },
  { value: "north_dakota", label: "Cuisine of North Dakota" },
  { value: "omaha", label: "Cuisine of Omaha" },
  { value: "st_louis", label: "St. Louis" },
  { value: "wisconsin", label: "Cuisine of Wisconsin" },
  { value: "minnesotan", label: "Minnesotan" },
  { value: "new_england", label: "Cuisine of New England" },
  { value: "mid_atlantic", label: "Cuisine of the Mid-Atlantic United States" },
  { value: "baltimore", label: "Cuisine of Baltimore" },
  { value: "belizean", label: "Belizean" },
  { value: "costa_rican", label: "Costa Rican" },
  { value: "salvadoran", label: "Salvadoran" },
  { value: "guatemalan", label: "Guatemalan" },
  { value: "honduran", label: "Honduran" },
  { value: "nicaraguan", label: "Nicaraguan" },
  { value: "panamanian", label: "Panamanian" },
  { value: "argentinian", label: "Argentinian" },
  { value: "bolivian", label: "Bolivian" },
  { value: "brazilian", label: "Brazilian" },
  { value: "chilean", label: "Chilean" },
  { value: "colombian", label: "Colombian" },
  { value: "muisca", label: "Muisca" },
  { value: "ecuadorian", label: "Ecuadorian" },
  { value: "french_guianan", label: "French Guianan" },
  { value: "guyanese", label: "Guyanese" },
  { value: "paraguayan", label: "Paraguayan" },
  { value: "asuncion", label: "Cuisine of Asunción" },
  { value: "peruvian", label: "Peruvian" },
  { value: "peruvian_chinese", label: "Peruvian-Chinese" },
  { value: "inca", label: "Inca" },
  { value: "surinamese", label: "Surinamese" },
  { value: "uruguayan", label: "Uruguayan" },
  { value: "montevideo", label: "Cuisine of Montevideo" },
  { value: "venezuelan", label: "Venezuelan" },
  { value: "afghan", label: "Afghan" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "bengali", label: "Bengali" },
  { value: "bhutanese", label: "Bhutanese" },
  { value: "hazaragi", label: "Hazaragi" },
  { value: "maldivian", label: "Maldivian" },
  { value: "nepalese", label: "Nepalese" },
  { value: "newari", label: "Newari" },
  { value: "sri_lankan", label: "Sri Lankan" },
  { value: "sylheti", label: "Sylheti" },
  { value: "russian", label: "Russian" },
  { value: "bruneian", label: "Bruneian" },
  { value: "burmese", label: "Burmese" },
  { value: "cambodian", label: "Cambodian" },
  { value: "christmas_island", label: "Christmas Island" },
  { value: "east_timor", label: "East Timor" },
  { value: "eastern_arabian", label: "Eastern Arabian" },
  { value: "bahraini", label: "Bahraini" },
  { value: "emirati", label: "Emirati" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "omani", label: "Omani" },
  { value: "qatari", label: "Qatari" },
  { value: "saudi_arabian", label: "Saudi Arabian" },
  { value: "yemeni", label: "Yemeni" },
  { value: "levantine", label: "Levantine" },
  { value: "iraqi", label: "Iraqi" },
  { value: "kurdish", label: "Kurdish" },
  { value: "israeli", label: "Israeli" },
  { value: "ancient_israelite", label: "Ancient Israelite" },
  { value: "jordanian", label: "Jordanian" },
  { value: "lebanese", label: "Lebanese" },
  { value: "mizrahi_jewish", label: "Mizrahi Jewish" },
  { value: "palestinian", label: "Palestinian" },
  { value: "syrian", label: "Syrian" },
  { value: "syrian_jewish", label: "Syrian Jewish" },
  { value: "assyrian", label: "Assyrian" },
  { value: "caucasian", label: "Caucasian" },
  { value: "armenian", label: "Armenian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "circassian", label: "Circassian" },
  { value: "georgian", label: "Georgian" },
  { value: "iranian", label: "Iranian" },
  { value: "caspian", label: "Caspian" },
  { value: "turkish", label: "Turkish" },
  { value: "pontic_greek", label: "Pontic Greek" },
  { value: "austrian", label: "Austrian" },
  { value: "viennese", label: "Viennese" },
  { value: "czech", label: "Czech" },
  { value: "hungarian", label: "Hungarian" },
  { value: "liechtensteiner", label: "Liechtensteiner" },
  { value: "polish", label: "Polish" },
  { value: "silesian", label: "Silesian" },
  { value: "slovak", label: "Slovak" },
  { value: "slovenian", label: "Slovenian" },
  { value: "swiss", label: "Swiss" },
  { value: "german", label: "German" },
  { value: "russian", label: "Russian" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "cossack", label: "Cossack" },
  { value: "moldovan", label: "Moldovan" },
  { value: "gagauz", label: "Gagauz" },
  { value: "romani", label: "Romani" },
  { value: "estonian", label: "Estonian" },
  { value: "latvian", label: "Latvian" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "livonian", label: "Livonian" },
  { value: "british", label: "British" },
  { value: "northern_irish", label: "Northern Irish" },
  { value: "scottish", label: "Scottish" },
  { value: "welsh", label: "Welsh" },
  { value: "irish", label: "Irish" },
  { value: "finnish", label: "Finnish" },
  { value: "icelandic", label: "Icelandic" },
  { value: "norwegian", label: "Norwegian" },
  { value: "sami", label: "Sami" },
  { value: "swedish", label: "Swedish" },
  { value: "danish", label: "Danish" },
  { value: "cypriot", label: "Cypriot" },
  { value: "balkan", label: "Balkan" },
  { value: "albanian", label: "Albanian" },
  { value: "aromanian", label: "Aromanian" },
  { value: "bosnian", label: "Bosnian" },
  { value: "croatian", label: "Croatian" },
  { value: "greek", label: "Greek" },
  { value: "macedonian", label: "Macedonian" },
  { value: "italian", label: "Italian" },
  { value: "maltese", label: "Maltese" },
  { value: "portuguese", label: "Portuguese" },
  { value: "sammarinese", label: "Sammarinese" },
  { value: "spanish", label: "Spanish" },
  { value: "belgian", label: "Belgian" },
  { value: "dutch", label: "Dutch" },
  { value: "french", label: "French" },
  { value: "basque", label: "Basque" },
  { value: "fast_food", label: "Fast Food" },
  { value: "fusion_cuisine", label: "Fusion Cuisine" },
  { value: "haute_cuisine", label: "Haute Cuisine" },
  { value: "molecular_gastronomy", label: "Molecular Gastronomy" },
  { value: "note_by_note_cuisine", label: "Note by Note Cuisine" },
  { value: "nouvelle_cuisine", label: "Nouvelle Cuisine" },
  { value: "vegan_cuisine", label: "Vegan Cuisine" },
  { value: "vegetarian_cuisine", label: "Vegetarian Cuisine" },
  { value: "indian_vegetarian_cuisine", label: "Indian Vegetarian Cuisine" },
  { value: "street_food", label: "Street Food" },
  { value: "burger", label: "Burger" },
  { value: "sandwiches", label: "Sandwiches" },
  { value: "hamburgers", label: "Hamburgers" },
  { value: "tacos", label: "Tacos" },
  { value: "hot_dogs", label: "Hot Dogs" },
  { value: "ice_cream", label: "Ice Cream" },
  { value: "beer", label: "Beer" },
  { value: "wine", label: "Wine" },
  { value: "cocktails", label: "Cocktails" },
  { value: "sake", label: "Sake" },
];

const seedDishes = [
  { value: "Pizza", label: "Pizza" },
  { value: "Burger", label: "Burger" },
  { value: "Sushi", label: "Sushi" },
  { value: "Pasta", label: "Pasta" },
  { value: "Tacos", label: "Tacos" },
  { value: "Salad", label: "Salad" },
  { value: "Ramen", label: "Ramen" },
  { value: "Paella", label: "Paella" },
  { value: "Curry", label: "Curry" },
  { value: "Steak", label: "Steak" },
  { value: "Lasagna", label: "Lasagna" },
  { value: "Dumplings", label: "Dumplings" },
  { value: "Pho", label: "Pho" },
  { value: "Falafel", label: "Falafel" },
  { value: "Gyros", label: "Gyros" },
  { value: "Burrito", label: "Burrito" },
  { value: "Pancakes", label: "Pancakes" },
  { value: "Waffles", label: "Waffles" },
  { value: "Croissant", label: "Croissant" },
  { value: "Bagel", label: "Bagel" },
  { value: "Donuts", label: "Donuts" },
  { value: "Hot Dog", label: "Hot Dog" },
  { value: "Fried Chicken", label: "Fried Chicken" },
  { value: "Barbecue", label: "Barbecue" },
  { value: "Fish and Chips", label: "Fish and Chips" },
  { value: "Tofu Stir Fry", label: "Tofu Stir Fry" },
  { value: "Risotto", label: "Risotto" },
  { value: "Biryani", label: "Biryani" },
  { value: "Pad Thai", label: "Pad Thai" },
  { value: "Peking Duck", label: "Peking Duck" },
  { value: "Spring Rolls", label: "Spring Rolls" },
  { value: "Fajitas", label: "Fajitas" },
  { value: "Enchiladas", label: "Enchiladas" },
  { value: "Quiche", label: "Quiche" },
  { value: "Tiramisu", label: "Tiramisu" },
  { value: "Cheesecake", label: "Cheesecake" },
  { value: "Baklava", label: "Baklava" },
  { value: "Apple Pie", label: "Apple Pie" },
  { value: "Churros", label: "Churros" },
  { value: "Brownies", label: "Brownies" },
  { value: "Macarons", label: "Macarons" },
  { value: "Gelato", label: "Gelato" },
  { value: "Sorbet", label: "Sorbet" },
  { value: "Crepes", label: "Crepes" },
  { value: "Poutine", label: "Poutine" },
  { value: "Shepherd's Pie", label: "Shepherd's Pie" },
  { value: "Carbonara", label: "Carbonara" },
  { value: "Ratatouille", label: "Ratatouille" },
  { value: "Bruschetta", label: "Bruschetta" },
  { value: "Schnitzel", label: "Schnitzel" },
  { value: "Kebab", label: "Kebab" },
  { value: "Bao Buns", label: "Bao Buns" },
  { value: "Dim Sum", label: "Dim Sum" },
  { value: "Ceviche", label: "Ceviche" },
  { value: "Chow Mein", label: "Chow Mein" },
  { value: "Kimchi", label: "Kimchi" },
  { value: "Bulgogi", label: "Bulgogi" },
  { value: "Goulash", label: "Goulash" },
  { value: "Pierogi", label: "Pierogi" },
  { value: "Borscht", label: "Borscht" },
  { value: "Stroopwafel", label: "Stroopwafel" },
  { value: "Moussaka", label: "Moussaka" },
  { value: "Empanadas", label: "Empanadas" },
  { value: "Arepa", label: "Arepa" },
  { value: "Pupusa", label: "Pupusa" },
  { value: "Samosa", label: "Samosa" },
  { value: "Kofta", label: "Kofta" },
  { value: "Shawarma", label: "Shawarma" },
  { value: "Hummus", label: "Hummus" },
  { value: "Tabbouleh", label: "Tabbouleh" },
  { value: "Dal", label: "Dal" },
  { value: "Tikka Masala", label: "Tikka Masala" },
  { value: "Butter Chicken", label: "Butter Chicken" },
  { value: "Rogan Josh", label: "Rogan Josh" },
  { value: "Vindaloo", label: "Vindaloo" },
  { value: "Jambalaya", label: "Jambalaya" },
  { value: "Gumbo", label: "Gumbo" },
  { value: "Po' Boy", label: "Po' Boy" },
  { value: "Beignets", label: "Beignets" },
  { value: "Fondue", label: "Fondue" },
  { value: "Raclette", label: "Raclette" },
  { value: "Sauerbraten", label: "Sauerbraten" },
  { value: "Wiener Schnitzel", label: "Wiener Schnitzel" },
  { value: "Spätzle", label: "Spätzle" },
  { value: "Rösti", label: "Rösti" },
  { value: "Frikadellen", label: "Frikadellen" },
  { value: "Coq au Vin", label: "Coq au Vin" },
  { value: "Bouillabaisse", label: "Bouillabaisse" },
  { value: "Escargot", label: "Escargot" },
  { value: "Ratatouille", label: "Ratatouille" },
  { value: "Gazpacho", label: "Gazpacho" },
  { value: "Pa amb tomàquet", label: "Pa amb tomàquet" },
  { value: "Tortilla Española", label: "Tortilla Española" },
  { value: "Lechon", label: "Lechon" },
  { value: "Adobo", label: "Adobo" },
  { value: "Sinigang", label: "Sinigang" },
  { value: "Banh Mi", label: "Banh Mi" },
  { value: "Pho", label: "Pho" },
  { value: "Tom Yum", label: "Tom Yum" },
  { value: "Massaman Curry", label: "Massaman Curry" },
];

const locationTypeData = [
  { value: "restaurant", label: "Restaurant" },
  { value: "takeaway", label: "Takeaway" },
  { value: "bar", label: "Bar" },
  { value: "cafe", label: "Cafe" },
  { value: "pub", label: "Pub" },
];

async function main() {
  console.log(`Start seeding ...`);

  for (const c of seedCuisines) {
    const cuisine = await prisma.cuisine.upsert({
      where: { value: c.value },
      update: {},
      create: c,
    });
    const wasCreated = cuisine.createdAt === cuisine.updatedAt;

    if (wasCreated) {
      console.log(`Created new cuisine with name: ${cuisine.label}`);
    }
  }

  for (const l of locationTypeData) {
    const locationType = await prisma.locationType.upsert({
      where: { value: l.value },
      update: {},
      create: l,
    });
    console.log(`Created location with id: ${locationType.id}`);
  }

  const deleteDishes = await prisma.dish.findMany({
    where: {
      location: {
        none: {},
      },
    },
  });

  for (const dish in deleteDishes) {
    await prisma.dish.delete({
      where: {},
    });
  }

  for (const d of seedDishes) {
    const dish = await prisma.dish.create({
      data: d,
    });
    console.log(`Created dish with id: ${dish.id}`);
  }
  console.log(`Seeding finished.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
